wavs=[
  'Air horn.wav',
  'Aoooga.wav',
  'Baby Giggle 1.wav',
  'Baby Giggle 2.wav',
  'Baby Giggle 3.wav',
  'Bannana Peel Slip 1.wav',
  'Bannana Peel Slip 2.wav',
  'Bicycle Horn.wav',
  'Billy Goat Bleat.wav',
  'Blow Nose.wav',
  'Boing.wav',
  'Boink.wav',
  'Bubble Pop.wav',
  'Burp 1.wav',
  'Burp 10.wav',
  'Burp 2.wav',
  'Burp 3.wav',
  'Burp 4.wav',
  'Burp 5.wav',
  'Burp 6.wav',
  'Burp 7.wav',
  'Burp 8.wav',
  'Burp 9.wav',
  'Cartoon Enlarge.wav',
  'Cartoon Eye Blink.wav',
  'Cartoon Fall.wav',
  'Cartoon Flip.wav',
  'Cartoon Head Shake No.wav',
  'Cartoon Head Shake Yes.wav',
  'Cartoon Jump.wav',
  'Cartoon Scramble.wav',
  'Cartoon Shrink.wav',
  'Cartoon Slip.wav',
  'Cartoon Whistle.wav',
  'Chipmunk Argue.wav',
  'Chipmunk Giggle.wav',
  'Circus 1.wav',
  'Circus 2.wav',
  'Clown Nose.wav',
  'Comedy Ruler Twang.wav',
  'Cow Bell.wav',
  'Cow Moo.wav',
  'Crowd Laugh 1.wav',
  'Crowd Laugh 2.wav',
  'Crowd Laugh 3.wav',
  'Crowd Laugh 4.wav',
  'Crowd Laugh 5.wav',
  'Crowd Laugh 6.wav',
  'Ding Ding Ding.wav',
  'Donkey.wav',
  'Drum Roll.wav',
  'Elephant Trumpet.wav',
  'Fart 1.wav',
  'Fart 10.wav',
  'Fart 2.wav',
  'Fart 3.wav',
  'Fart 4.wav',
  'Fart 5.wav',
  'Fart 6.wav',
  'Fart 7.wav',
  'Fart 8.wav',
  'Fart 9.wav',
  'Funny Chicken.wav',
  'Funny Monkey.wav',
  'Goofy Laugh 1.wav',
  'Goofy Laugh 2.wav',
  'Hiccups Baby.wav',
  'Hiccups Female.wav',
  'Hiccups Kid.wav',
  'Hiccups Man.wav',
  'Jump.wav',
  'Kid Laugh 1.wav',
  'Kid Laugh 2.wav',
  'Kid Laugh 3.wav',
  'Kid Laugh 4.wav',
  'Kid Laugh 5.wav',
  'Lady Laugh 1.wav',
  'Lady Laugh 2.wav',
  'Lady Laugh 3.wav',
  'Lady Laugh 4.wav',
  'Man Laugh 1.wav',
  'Man Laugh 2.wav',
  'Man Laugh 3.wav',
  'Man Laugh 4.wav',
  'Party Horn 1.wav',
  'Party Horn 2.wav',
  'Party Horn 3.wav',
  'Pig.wav',
  'Pop.wav',
  'Quack Quack.wav',
  'Rip Underpants 1.wav',
  'Rip Underpants 2.wav',
  'Sad Trombone 1.wav',
  'Sad Trombone 2.wav',
  'Slide.wav',
  'Snap.wav',
  'SoundBible.com.url',
  'Spring 1.wav',
  'Spring 2.wav'
];
